// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeter.proto

package org.wrj.haifa.grpc;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcJavaDemo.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
